import type { Project } from '@/types'

/**
 * Portfolio Projects Data
 * Rozšířená datová struktura pro projekty s detailními informacemi
 * pro Shared Element Transition layout.
 */
export const PORTFOLIO_PROJECTS: Project[] = [
  {
    id: 'bulldogo',
    title: 'Bulldogo.cz',
    tech: 'Webová aplikace',
    description: 'Platforma pro inzerci služeb – propojili jsme zákazníky s poskytovateli',
    link: 'https://bulldogo.cz',
    screenshot: '/screenshots/bulldogo.png',
    allowIframe: false,
    year: '2024',
    client: 'Bulldogo s.r.o.',
    story: 'Bulldogo vzniklo z potřeby vytvořit transparentní platformu, kde se poskytovatelé služeb mohou prezentovat a zákazníci snadno najít to, co potřebují. Chtěli jsme eliminovat chaos v inzerci a vytvořit moderní, uživatelsky přívětivé prostředí.',
    requirements: [
      'Intuitivní rozhraní pro vkládání a správu inzerátů',
      'Pokročilé vyhledávání a filtrování služeb podle kategorií',
      'Responzivní design fungující na všech zařízeních',
      'Rychlé načítání i při velkém množství dat',
      'Systém hodnocení a recenzí',
    ],
    technicalDetails: 'Aplikace byla postavena s důrazem na výkon a škálovatelnost. Použili jsme React pro dynamické uživatelské rozhraní, Next.js pro server-side rendering a optimalizaci SEO. Backend běží na Node.js s PostgreSQL databází. Implementovali jsme full-text search pro rychlé vyhledávání a Redis cache pro optimalizaci dotazů.',
    technologies: ['Next.js', 'React', 'TypeScript', 'PostgreSQL', 'Redis', 'Node.js', 'Tailwind CSS'],
    challenges: [
      'Optimalizace full-text search pro české znaky a vyhledávání',
      'Implementace real-time notifikací pro nové inzeráty',
      'Škálování databáze pro tisíce současných uživatelů',
    ],
  },
  {
    id: 'uctarna',
    title: 'Účtárna',
    tech: 'Firemní systém',
    description: 'Moderní účetní systém, kde se vyznáte na první pohled',
    link: 'https://www.uctarna.fun',
    screenshot: '/screenshots/uctarna.png',
    allowIframe: true,
    year: '2025',
    client: 'Interní projekt',
    story: 'Účtárna vznikla jako odpověď na přetížené a nepřehledné účetní systémy. Cílem bylo vytvořit nástroj, který bude jednoduchý, rychlý a hlavně příjemný na používání. Chtěli jsme ukázat, že i účetnictví může být sexy.',
    requirements: [
      'Přehledný dashboard s key metrikami',
      'Automatické párování faktur a plateb',
      'Export dat v různých formátech (XML, CSV, PDF)',
      'Přístupová práva pro různé role (účetní, vedení, external)',
      'Mobilní aplikace pro schvalování faktur',
    ],
    technicalDetails: 'Systém je postaven na moderním tech stacku s React frontendem a Python FastAPI backendem. Využíváme PostgreSQL pro relační data a MongoDB pro dokumenty. Implementovali jsme OCR pro automatické čtení faktur pomocí Google Cloud Vision API. Pro real-time aktualizace používáme WebSocket spojení.',
    technologies: ['React', 'TypeScript', 'Python', 'FastAPI', 'PostgreSQL', 'MongoDB', 'Google Cloud Vision', 'WebSocket'],
    challenges: [
      'OCR rozpoznávání českých faktur s různými formáty',
      'Synchronizace dat s externí účetní legislativou',
      'Real-time collaboration při práci více uživatelů současně',
    ],
  },
  {
    id: 'extroworld',
    title: 'Extroworld',
    tech: 'Značková prezentace',
    description: 'Kreativní web pro moderní značku',
    link: 'https://extroworld.com',
    screenshot: '/screenshots/extroworld.png',
    allowIframe: true,
    year: '2024',
    client: 'Extroworld Brand',
    story: 'Extroworld je mladá, dynamická značka, která potřebovala web odpovídající její vizuální identitě. Chtěli něco odvážného, interaktivního a nezapomenutelného. Vytvořili jsme pro ně digitální zážitek, který perfektně odráží jejich DNA.',
    requirements: [
      'Silná vizuální identita s důrazem na animace',
      'Interaktivní 3D prvky',
      'Storytelling formou scrollu',
      'Video hero section',
      'Integrace s e-shopem',
    ],
    technicalDetails: 'Web využívá Three.js pro 3D animace a GSAP pro scroll-driven animace. Celá stránka je optimalizovaná pro výkon díky lazy loadingu a code splitting. Video obsah je hostován na vlastním CDN pro rychlé načítání. Použili jsme WebGL shadery pro custom vizuální efekty.',
    technologies: ['Next.js', 'Three.js', 'GSAP', 'WebGL', 'Framer Motion', 'TypeScript', 'Tailwind CSS'],
    challenges: [
      'Optimalizace 3D scény pro mobilní zařízení',
      'Synchronizace animací s scroll pozicí',
      'Balancování vizuálního bohatství s výkonem',
    ],
  },
  {
    id: 'podlahy-katalog',
    title: 'Podlahy Katalog',
    tech: 'Produktový katalog',
    description: 'Přehledný katalog produktů s elegantním designem',
    link: 'https://podlahy.vercel.app',
    screenshot: '/screenshots/podlahy.png',
    allowIframe: true,
    year: '2024',
    client: 'Podlahy s.r.o.',
    story: 'Firma prodávající podlahy potřebovala přehledný online katalog, kde zákazníci snadno najdou to, co hledají. Starý web byl pomalý a nepřehledný. Vytvořili jsme moderní, rychlý katalog s pokročilým filtrováním.',
    requirements: [
      'Filtrace podle typu, barvy, rozměrů a ceny',
      'Galerie s high-quality fotkami',
      'Rychlé vyhledávání',
      'Košík a kalkulačka množství',
      'Admin rozhraní pro správu produktů',
    ],
    technicalDetails: 'Katalog běží na Next.js s Incremental Static Regeneration pro rychlé načítání produktových stránek. Obrázky jsou optimalizované pomocí Next.js Image komponenty a hostované na Cloudinary CDN. Elasticsearch poskytuje lightning-fast search a faceted filtering.',
    technologies: ['Next.js', 'React', 'Elasticsearch', 'Cloudinary', 'Prisma', 'PostgreSQL', 'Tailwind CSS'],
    challenges: [
      'Optimalizace tisíců produktových fotek',
      'Implementace komplexního faceted search',
      'Výpočet reálných dodacích lhůt podle skladu',
    ],
  },
  {
    id: 'ejdry',
    title: 'Ejdry.cz',
    tech: 'Firemní web',
    description: 'Profesionální prezentace firmy',
    link: 'http://ejdry.cz',
    screenshot: '/screenshots/ejdry.png',
    allowIframe: false,
    year: '2023',
    client: 'EJDRY s.r.o.',
    story: 'Tradiční firma s dlouholetou historií potřebovala modernizovat svou online prezentaci. Cílem bylo představit firmu mladším generacím, ale zároveň zachovat důvěryhodnost a profesionalitu.',
    requirements: [
      'Čistý, profesionální design',
      'Prezentace služeb a referencí',
      'Kontaktní formulář',
      'SEO optimalizace',
      'Snadná správa obsahu pro klienta',
    ],
    technicalDetails: 'Jednoduchý, ale efektivní web postavený na Next.js s statickým generováním pro maximální výkon. Obsah je spravován přes Markdown soubory, které klient snadno edituje. Formulář je zabezpečený proti spamu pomocí reCAPTCHA.',
    technologies: ['Next.js', 'React', 'Markdown', 'reCAPTCHA', 'Vercel'],
    challenges: [
      'Migrace obsahu ze starého WordPressu',
      'Školení klienta pro správu Markdown obsahu',
      'SEO optimalizace pro konkurenční odvětví',
    ],
  },
  {
    id: 'raj-mazlicku',
    title: 'Ráj mazlíčků',
    tech: 'E-shop a web',
    description: 'Kompletní web pro rodinnou firmu z Karlovarska – rozkvétají s námi od roku 2025',
    link: 'https://rajmazlicku.vercel.app',
    screenshot: '/screenshots/rajmazlicku.png',
    allowIframe: true,
    year: '2025',
    client: 'Ráj mazlíčků',
    story: 'Rodinná firma z Karlovarska, která se specializuje na chovatelské potřeby, potřebovala vstoupit do online světa. Chtěli e-shop, který bude jednoduchý na ovládání jak pro ně, tak pro jejich zákazníky. Od ledna 2025 s námi rozkvetli online a prodeje rostou.',
    requirements: [
      'Kompletní e-shop s platební bránou',
      'Katalog produktů s kategorizací',
      'Blog s radami pro chovatele',
      'Integrace se skladovým systémem',
      'Snadná správa objednávek',
    ],
    technicalDetails: 'E-shop běží na Next.js s vlastním backendem v Node.js. Pro platby používáme Stripe a ComGate. Produkty jsou synchronizované se skladovým systémem přes API. Blog je powered by Contentful CMS. Implementovali jsme automatické emailové notifikace pro zákazníky.',
    technologies: ['Next.js', 'React', 'Node.js', 'Stripe', 'ComGate', 'Contentful', 'PostgreSQL', 'TypeScript'],
    challenges: [
      'Integrace s legacy skladovým systémem',
      'Automatická synchronizace dostupnosti produktů',
      'Handling více platebních bran současně',
      'Email marketing automatizace',
    ],
  },
]
